name: Test
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code from repo'
      uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build .