name: Test
on:
  schedule:
    - cron:  '* * * 1/10 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code from repo'
      uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build .